const encoder=new TextEncoder(),SESSION_SECONDS=28800,COOKIE='__Host-hsv-admin';
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const fail=(s,m)=>{throw new HttpError(s,m)};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const digest=async value=>hex(await crypto.subtle.digest('SHA-256',encoder.encode(value)));
export async function passwordHash(password,salt,pepper){const key=await crypto.subtle.importKey('raw',encoder.encode(password+'\0'+pepper),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:600000,hash:'SHA-256'},key,256))}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
function response(data,status=200,headers={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
function cookie(token,age=SESSION_SECONDS){return `${COOKIE}=${token}; Path=/; Max-Age=${age}; HttpOnly; Secure; SameSite=Strict`}
function origin(request){const expected=new URL(request.url).origin;if(request.headers.get('Origin')!==expected||request.headers.get('X-Hsv-Request')!=='1')fail(403,'Please use the dashboard to make changes.')}
async function json(request){if(!request.headers.get('Content-Type')?.startsWith('application/json'))fail(415,'Expected a JSON request.');if(Number(request.headers.get('Content-Length'))>20000)fail(413,'Request is too large.');const t=await request.text();if(t.length>20000)fail(413,'Request is too large.');try{return JSON.parse(t)}catch{fail(400,'Invalid request.')}}
function password(value){if(typeof value!=='string'||value.length<12||value.length>256)fail(400,'Use a password between 12 and 256 characters.');return value}
async function call(env,path,method='GET',body,prefer='return=representation'){
 if(!env.SUPABASE_URL||!env.SUPABASE_SECRET_KEY)fail(503,'The dashboard connection is not configured yet.');
 const headers={apikey:env.SUPABASE_SECRET_KEY,'Content-Type':'application/json',Prefer:prefer};
 if(!env.SUPABASE_SECRET_KEY.startsWith('sb_secret_'))headers.Authorization='Bearer '+env.SUPABASE_SECRET_KEY;
 const r=await (env.fetch||fetch)(env.SUPABASE_URL+'/rest/v1/'+path,{method,headers,...(body!==undefined?{body:JSON.stringify(body)}:{})});
 if(!r.ok){if(r.status===409)fail(409,'This record already exists. Please reload.');throw new Error('Database request failed ('+r.status+')');}
 return r.status===204?null:r.json();
}
const q=value=>encodeURIComponent(String(value));
async function admin(env){return (await call(env,'hsv_admins?username=eq.camron&limit=1'))[0]}
async function session(request,env){const token=request.headers.get('Cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const s=(await call(env,'hsv_sessions?token_hash=eq.'+await digest(token)+'&expires_at=gt.'+Date.now()+'&limit=1'))[0];if(!s)return null;const a=await admin(env);return a&&s.auth_version===a.auth_version?s:null;}
async function requireSession(request,env,mutate=false){const s=await session(request,env);if(!s)fail(401,'Please log in again.');if(mutate){origin(request);if(!equal(request.headers.get('X-CSRF-Token'),s.csrf))fail(403,'Your session needs to be refreshed. Please reload the dashboard.')}return s}
async function createSession(env,authVersion){const token=random(),csrf=random();await call(env,'hsv_sessions?expires_at=lt.'+Date.now(),'DELETE',undefined,'return=minimal');await call(env,'hsv_sessions','POST',{token_hash:await digest(token),username:'camron',csrf,expires_at:Date.now()+SESSION_SECONDS*1000,auth_version:authVersion});return response({authenticated:true,username:'camron',csrf},200,{'Set-Cookie':cookie(token)})}
async function rateLimit(request,env){const key=await digest(request.headers.get('x-vercel-forwarded-for')?.split(',')[0]?.trim()||'unknown');const attempts=await call(env,'rpc/hsv_login_attempt','POST',{p_key:key});if(attempts>10)fail(429,'Too many login attempts. Please try again in 15 minutes.');return key}
function text(value,max,required=false){if(typeof value!=='string')value='';value=value.trim();if((required&&!value)||value.length>max)fail(400,required?'Please add a project title (up to 150 characters).':'One of the fields is too long.');return value}
function safeUrl(value,image=false){const s=text(value,2000);if(!s)return '';if(image&&/^\/(?:assets|media)\/[a-zA-Z0-9_.-]+$/.test(s))return s;try{const u=new URL(s);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)fail(400,'Use an https:// or http:// link.');return u.href}catch{fail(400,image?'Enter a full image URL or upload an image.':'Enter a full website or video URL, including https://.')}}
export function validateProject(value){if(!['websites','logos','drone','seo','clients'].includes(value.category))fail(400,'Choose a valid category.');if(value.category==='clients'&&!text(value.image,2000))fail(400,'Upload a logo or add its image URL.');const n=Number(value.sort_order);if(!Number.isInteger(n)||n<0||n>9999)fail(400,'Display order must be a number between 0 and 9999.');return{category:value.category,title:text(value.title,150,true),type:text(value.type,120),image:safeUrl(value.image,true),url:safeUrl(value.url),description:text(value.description,4000),video:value.category==='drone'&&!!value.video,featured:value.category==='websites'&&!!value.featured,published:!!value.published,sort_order:n}}
function asProject(p){return{...p,video:!!p.video,featured:!!p.featured,published:!!p.published}}
async function api(request,env){
 const path=new URL(request.url).pathname,method=request.method;
 if(path==='/api/portfolio'&&method==='GET'){const rows=await call(env,'hsv_projects?published=eq.true&order=sort_order,updated_at.desc,id');return response({projects:rows.filter(p=>p.category!=='clients'),clients:rows.filter(p=>p.category==='clients')});}
 if(path==='/api/admin/status'&&method==='GET'){const a=await admin(env),s=await session(request,env);return response({setupRequired:!a,canSetup:!!env.ADMIN_SETUP_TOKEN,authenticated:!!s,username:s?.username,csrf:s?.csrf});}
 if(path==='/api/admin/setup'&&method==='POST'){origin(request);await rateLimit(request,env);const data=await json(request);if(!env.ADMIN_SETUP_TOKEN||env.ADMIN_SETUP_TOKEN.length<32||!equal(data.setup_token,env.ADMIN_SETUP_TOKEN))fail(403,'Enter the setup token saved in your Vercel settings.');if(await admin(env))fail(409,'Your account is already set up. Please log in.');const p=password(data.password);if(!env.PASSWORD_PEPPER||env.PASSWORD_PEPPER.length<32)fail(503,'Login is not configured yet.');const salt=random();await call(env,'hsv_admins','POST',{username:'camron',password_hash:await passwordHash(p,salt,env.PASSWORD_PEPPER),salt,updated_at:Date.now(),auth_version:1});return createSession(env,1);}
 if(path==='/api/admin/login'&&method==='POST'){origin(request);await rateLimit(request,env);const data=await json(request),a=await admin(env);if(!a)fail(409,'Create your password first.');if(!env.PASSWORD_PEPPER)fail(503,'Login is not configured yet.');const pass=typeof data.password==='string'?data.password:'';if(pass.length>256)fail(401,'Username or password is incorrect.');const hash=await passwordHash(pass,a.salt,env.PASSWORD_PEPPER);if(data.username?.trim().toLowerCase()!=='camron'||!equal(hash,a.password_hash))fail(401,'Username or password is incorrect.');return createSession(env,a.auth_version);}
 if(path==='/api/admin/logout'&&method==='POST'){const s=await requireSession(request,env,true);await call(env,'hsv_sessions?token_hash=eq.'+q(s.token_hash),'DELETE',undefined,'return=minimal');return response({loggedOut:true},200,{'Set-Cookie':cookie('',0)});}
 if(path==='/api/admin/password'&&method==='POST'){await requireSession(request,env,true);await rateLimit(request,env);const data=await json(request),a=await admin(env),p=password(data.password);if(typeof data.current_password!=='string'||data.current_password.length>256||!equal(await passwordHash(data.current_password,a.salt,env.PASSWORD_PEPPER),a.password_hash))fail(401,'Your current password is incorrect.');const salt=random(),next=a.auth_version+1;const rows=await call(env,'hsv_admins?username=eq.camron&auth_version=eq.'+a.auth_version,'PATCH',{password_hash:await passwordHash(p,salt,env.PASSWORD_PEPPER),salt,updated_at:Date.now(),auth_version:next});if(!rows.length)fail(409,'Your password changed in another session. Please log in again.');return createSession(env,next);}
 if(path==='/api/admin/projects'&&method==='GET'){await requireSession(request,env);return response({projects:await call(env,'hsv_projects?order=sort_order,updated_at.desc,id')});}
 if(path==='/api/admin/projects'&&method==='POST'){await requireSession(request,env,true);const data=validateProject(await json(request)),project={id:crypto.randomUUID(),...data,version:1,updated_at:Date.now()};await call(env,'hsv_projects','POST',project);return response({project},201);}
 const match=path.match(/^\/api\/admin\/projects\/([a-zA-Z0-9_-]{1,100})$/);
 if(match&&['PUT','DELETE'].includes(method)){await requireSession(request,env,true);const body=await json(request);if(!Number.isInteger(body.version)||body.version<1)fail(400,'Reload this project before saving.');const filter='hsv_projects?id=eq.'+q(match[1])+'&version=eq.'+body.version;let rows;if(method==='PUT'){const data={...validateProject(body),version:body.version+1,updated_at:Date.now()};rows=await call(env,filter,'PATCH',data);}else rows=await call(env,filter,'DELETE');if(!rows.length)fail(409,'This project changed in another session. Reload before saving or deleting.');return response(method==='PUT'?{project:rows[0]}:{deleted:true});}
 if(path==='/api/admin/upload'&&method==='POST'){
  await requireSession(request,env,true);const data=await json(request),types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'};if(!types[data.type]||!Number.isInteger(data.size)||data.size<1||data.size>8388608)fail(400,'Choose a JPG, PNG, WebP, or GIF image under 8 MB.');
  const key=crypto.randomUUID()+'.'+types[data.type],base=env.SUPABASE_URL+'/storage/v1',headers={apikey:env.SUPABASE_SECRET_KEY,'Content-Type':'application/json'};if(!env.SUPABASE_SECRET_KEY.startsWith('sb_secret_'))headers.Authorization='Bearer '+env.SUPABASE_SECRET_KEY;
  const r=await(env.fetch||fetch)(base+'/object/upload/sign/hsv-media/'+key,{method:'POST',headers,body:'{}'});if(!r.ok)fail(503,'Image storage is not configured yet.');const signed=await r.json();const uploadUrl=new URL(base+signed.url);if(uploadUrl.origin!==new URL(env.SUPABASE_URL).origin||!uploadUrl.searchParams.get('token'))fail(503,'Image upload could not be prepared.');return response({uploadUrl:uploadUrl.href,url:base+'/object/public/hsv-media/'+key},201);
 }
 return response({error:'Not found.'},404);
}
export async function handleApi(request,env){try{return await api(request,env)}catch(e){if(!(e instanceof HttpError))console.error('Portfolio API failure');return response({error:e instanceof HttpError?e.message:'The dashboard could not reach storage. Please check setup and try again.'},e.status||503)}}
